---

- name: Start container
  docker_container:
    image: '{{ spark_docker_image }}'
    name: '{{ spark_docker_name }}'
    command: '{{ command }}'
    volumes: '{{ spark_volumes }}'
    state: started
    network_mode: host
    pull: true
    env: '{{ spark_docker_env }}'
