#!/usr/bin/env python

import click
import subprocess

from typing import Optional

from cluster import read_config, config_path


@click.command()
@click.argument('profile', required=False)
def main(profile: Optional[str]):
    """Start a cluster.
    """
    config = read_config(config_path, profile)

    config.write_terraform_vars()
    config.write_ansible_vars()

    subprocess.run(['terraform', 'apply'], cwd='terraform')
    subprocess.run(['ansible-playbook', 'deploy.yml'], cwd='ansible')


if __name__ == '__main__':
    main()
