---

- name: Deploy Spark
  hosts: spark
  gather_facts: no
  become: yes

  vars:
    ansible_python_interpreter: python3

  vars_files:
    - .config.ansible.json

  tasks:
    - include_role:
        name: spark