[tool.poetry]
name = "pyspark-deploy"
version = "0.1.0"
description = ""
authors = ["David McClure <davidwilliammcclure@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ansible = "^2.9.10"
jinja2 = "^2.11.2"
pyyaml = "^5.3.1"
cryptography = "^2.9.2"
pydantic = "^1.5.1"
ipython = "^7.16.1"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
