# https://taskfile.dev

version: '3'

tasks:
  setup: terraform init

  create: terraform apply

  destroy: terraform destroy

  webui: open http://`terraform output -raw master_dns`:8080

  login: >
    ssh -o StrictHostKeyChecking=no -t
    ubuntu@`terraform output -raw master_dns`