---

- name: Start container
  docker_container:
    image: '{{ spark_docker_image }}'
    name: '{{ name }}'
    command: '{{ command }}'
    volumes: '{{ spark_volumes }}'
    env: '{{ spark_docker_env }}'
    runtime: '{{ runtime|default("") }}'
    state: started
    network_mode: host
    pull: true
    timeout: 300
    comparisons:
      '*': ignore
