---

- name: Start container
  docker_container:
    image: '{{ docker_image }}'
    name: '{{ docker_name }}'
    command: '{{ command }}'
    volumes: '{{ spark_volumes }}'
    state: started
    network_mode: host
    pull: true
    restart_policy: always
    restart: true
    env: '{{ spark_docker_env }}'
