---

- name: Start the cluster
  hosts: spark
  gather_facts: no
  become: yes

  vars:
    ansible_python_interpreter: python3
    spark_home: /opt/spark
    data_dir: /data
    config_dir: /etc/spark

  tasks:
    - name: Wait for SSH connection
      wait_for_connection:

    - name: Gather facts, after SSH
      setup:

    # packer
    - name: Install docker-py
      pip:
        name: docker

    # packer?
    - name: Create directories
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '{{ data_dir }}'
        - '{{ config_dir }}'

    - name: Render Spark config
      template:
        src: 'templates/{{ item }}'
        dest: '{{ config_dir }}/{{ item }}'
      with_items:
        - spark-defaults.conf
        - spark-env.sh
        - log4j.properties

    # packer
    - name: Render Docker bash script
      copy:
        src: templates/docker-bash.sh
        dest: /home/{{ ansible_user }}/docker-bash.sh
        owner: '{{ ansible_user }}'
        mode: u+x

    # packer
    - name: Automatically connect to container on login
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: source ./docker-bash.sh

    # TODO: docker_login?
    - name: Log in to ECR
      shell: $(aws ecr get-login --no-include-email --region {{ aws_region }})
      environment:
        AWS_ACCESS_KEY_ID: '{{ aws_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ aws_secret_access_key }}'

    # TODO: Single play?
    - name: Start master
      include_tasks: start_container.yml
      when: '"master" in group_names'
      vars:
        name: spark-master
        # runtime: '{{ spark_master_docker_runtime }}'
        command: spark-class org.apache.spark.deploy.master.Master

    - name: Start workers
      include_tasks: start_container.yml
      when: '"workers" in group_names'
      vars:
        name: spark-worker
        # runtime: '{{ spark_worker_docker_runtime }}'
        command: >
          spark-class org.apache.spark.deploy.worker.Worker
          spark://{{ master_private_ip }}:7077