---

- name: Wait for SSH connection
  wait_for_connection:

- name: Gather facts, after SSH
  setup:

- name: apt-get update
  apt:
    update_cache: yes

- name: Install Docker
  include_role:
    name: geerlingguy.docker

- name: Install docker-py
  include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker

# TODO: Public?
- name: Make snapshot
  become: no
  register: ami
  local_action:
    module: ec2_ami
    instance_id: '{{ tf_instance_id }}'
    name: '{{ docker_ami_name }}'
    region: '{{ tf_aws_region }}'
    wait: yes

- debug:
    var: ami.image_id
