---

- name: Create node
  hosts: localhost
  tasks:
    - include_role:
        name: docker-ami
        tasks_from: create

- name: Configure image
  hosts: docker
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: docker-ami
        tasks_from: deploy

- name: Destroy node
  hosts: localhost
  tasks:
    - include_role:
        name: docker-ami
        tasks_from: destroy
