---

- name: Create node
  hosts: localhost
  tasks:
    - include_role:
        name: spark
        tasks_from: create_base

- name: Configure image
  hosts: docker
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: spark
        tasks_from: deploy_base

- name: Destroy node
  hosts: localhost
  tasks:
    - include_role:
        name: spark
        tasks_from: destroy_base
