---

- name: Create node
  hosts: localhost
  tasks:
    - include_role:
        name: spark
        tasks_from: ami_up

- name: Configure image
  hosts: docker
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: spark
        tasks_from: ami_deploy

- name: Destroy node
  hosts: localhost
  tasks:
    - include_role:
        name: spark
        tasks_from: ami_down
