---

- name: Create nodes
  hosts: localhost
  tasks:

    - terraform:
        project_path: ../terraform/spark-cluster
        state: present

    - meta: refresh_inventory

- name: Deploy Spark
  hosts: spark
  gather_facts: no
  become: yes
  roles:
    - spark-cluster
