---

- name: Create cluster
  hosts: localhost
  tasks:
    - include_role:
        name: spark
        tasks_from: cluster_up

- name: Deploy Spark
  hosts: spark
  gather_facts: no
  become: yes
  tasks:
    - include_role:
        name: spark
        tasks_from: cluster_deploy
