---

- name: Create node
  hosts: localhost
  tasks:

    - terraform:
        project_path: ../terraform/docker-ami
        state: present

    - meta: refresh_inventory

- name: Deploy Spark
  hosts: docker
  gather_facts: no
  become: yes
  roles:
    - docker-ami

- name: Destroy node
  hosts: localhost
  tasks:

    - terraform:
        project_path: ../terraform/docker-ami
        state: absent
