---

- name: Configure image
  hosts: docker
  gather_facts: no
  become: yes

  vars:
    ansible_python_interpreter: python3
    ami_name: docker-{{ ansible_date_time.epoch }}

  tasks:

    - name: Wait for SSH connection
      wait_for_connection:

    - name: Gather facts, after SSH
      setup:

    - name: apt-get update
      apt:
        update_cache: yes

    - name: Install Docker
      include_role:
        name: geerlingguy.docker

    - name: Install docker-py
      include_role:
        name: geerlingguy.pip
      vars:
        pip_package: python3-pip
        pip_install_packages:
          - name: docker

    - name: Create AMI
      become: no
      register: ami
      local_action:
        module: ec2_ami
        instance_id: '{{ tf_instance_id }}'
        name: '{{ ami_name }}'
        region: '{{ tf_aws_region }}'
        wait: yes

    - name: Render tfvars
      become: no
      local_action:
        module: lineinfile
        path: ./docker-ami.auto.tfvars
        line: docker_ami = "{{ ami.image_id }}"
        create: yes

    - debug:
        var: ami.image_id
